CC := gcc
CFLAGS := -l bls384_256

all: bls12_381_keygen bls12_381_export_pubkey bls_sign bls_verify bls_multi_sign

clean:
	/bin/rm bls12_381_keygen bls12_381_export_pubkey bls_sign bls_verify bls_multi_sign
